server:
  port: 8989
spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://193.112.100.103:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: abc123
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://193.112.100.103:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: abc123
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml